# People making us happy!
- href: http://twitter.com/barbaracones
  name: Barbara Wolff Dick
  gravatar: http://www.gravatar.com/avatar/f4fc1c7c96f36234841accc42b6c6378
- href: http://twitter.com/dwildt
  name: Daniel Wildt
  gravatar: http://www.gravatar.com/avatar/cf9ffac42374a74ccde477beccb9009b
- href: http://twitter.com/felipebcabral
  name: Felipe Cabral
  gravatar: http://www.gravatar.com/avatar/be967c5ae6246838fd93a47d0e17d7ed
- href: http://twitter.com/nataliarsand
  name: Natalia Arsand
  gravatar: http://www.gravatar.com/avatar/35364dd7392846bca6523cb71a71ae70
- href: http://twitter.com/bitbonsai
  name: Mauricio Wolff
  gravatar: http://www.gravatar.com/avatar/1d5d4c232779777398e3b56773d71121
- href: http://twitter.com/pedrobelleza
  name: Pedro Belleza
  gravatar: http://www.gravatar.com/avatar/18fe7037f6d14542f5de0a1714445dbb
- href: http://twitter.com/rafb3
  name: Rafael Bandeira
  gravatar: http://www.gravatar.com/avatar/6e333c5051ee580b75d9a20db899098d
